#!/bin/bash

# Update packages
sudo apt update -y

# Install kubectl
curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

# Install AWS CLI
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
sudo apt install -y unzip
unzip -o awscliv2.zip
sudo ./aws/install

# Install eksctl
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sudo mv /tmp/eksctl /usr/local/bin

# Verify installations
kubectl version --client
aws --version
eksctl version



#installation eks:(before set to security-->iamrole)
eksctl delete cluster --name simbu-cluster  --region ap-south-1 --node-type t3.micro --nodes 3



#Deleteion
kubectl delete pod
kubectl delete deployment.apps/
kubectl delete service/
eksctl delete cluster --name simbu-cluster  --region ap-south-1
terrform destroy
